
dist: bionic

sudo: false

language: cpp

cache:
  directories:
  - $HOME/.conan

compiler:
  - clang
  - gcc

install:
  - pip install --user conan>=1
  - conan user

script:
  - python build.py --pkg_mgr conan --build_type Debug --acquire --configure --build --test
