
dist: xenial

sudo: false

language: cpp

compiler:
  - clang
  - gcc

install:
  - pip install --user conan>=1
  - conan user

script:
  - python build.py --conan_install --conan_build --cmake_test --build_type Debug
