branches:
  only:
    - travis-appveyor

max_jobs: 1

image: Visual Studio 2017

install:
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake --version
  - cmd: conan --version
  - cmd: conan install ..
  - cmd: conan build --file ../conanfile.py

test_script:
  ctest
