version: 1.0.{build}

max_jobs: 1

image: Visual Studio 2017

cache:
  - '%USERPROFILE%\.conan -> appveyor.yml'

install:
- cmd: >-
    set PATH=%PATH%;%PYTHON%/Scripts/

    pip.exe install conan>=1

    conan user

build_script:
- cmd: >-
    python build.py --pkg_mgr conan --build_type Debug --acquire --build

test_script:
- cmd: >-
    python build.py --pkg_mgr conan --build_type Debug --test
