version: 1.0.{build}

max_jobs: 1

image: Visual Studio 2017

install:
- cmd: >-
    set PATH=%PATH%;%PYTHON%/Scripts/

    pip.exe install conan

    conan user

build_script:
- cmd: >-
    cmake --version

    conan --version

    mkdir build

    cd build

    conan export --path ../src/conan/sfml sfml/2.4.1@pascal/testing

    conan install --file ../conanfile.py --build=missing -s build_type=Debug

    conan build --file ../conanfile.py

test_script:
- cmd: ctest
