version: 1.0.{build}

max_jobs: 1

image: Visual Studio 2017

install:
- cmd: >-
    set PATH=%PATH%;%PYTHON%/Scripts/

    pip.exe install conan>=1

    conan user

build_script:
- cmd: >-
    python build.py --conan_install --conan_build --build_type Debug

test_script:
- cmd: >-
    python build.py --cmake_test --build_type Debug
