version: 1.0.{build}

max_jobs: 1

image: Visual Studio 2017

install:
- cmd: >-
    set PATH=%PATH%;%PYTHON%/Scripts/

    pip.exe install conan==0.27

    conan user

build_script:
- cmd: >-
    first-build.bat

test_script:
- cmd: >-
    cd build\win

    ctest
