version: 1.0.{build}

max_jobs: 1

image: Visual Studio 2019

cache:
  - c:\tools\vcpkg\installed -> appveyor.yml

build_script:
- cmd: >-
    python build.py --pkg_mgr vcpkg --build_type Debug --acquire --configure --build

test_script:
- cmd: >-
    python build.py --pkg_mgr vcpkg --build_type Debug --test
